name: up_chat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: null
  cupertino_icons: ^1.0.2
  dartz: 
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_screenutil: null
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  get_it: ^7.6.4
  google_fonts: null
  google_nav_bar: ^5.0.6
  shared_preferences: null
  smooth_page_indicator: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
